import { v4 as uuidv4 } from "uuid";

export const dummyMovies = [
  {
    id: uuidv4(),
    title: "Dipu Number 2",
    genere: "drama",
    rating: "8.9",
    year: "1996",
    desc: "An adventure story for young boys.",
  },
  {
    id: uuidv4(),
    title: "Monpura",
    genere: "drama",
    rating: "8.7",
    year: "2009",
    desc: "A housemaid is killed by a local landlord's son. His servant takes the blame for the murder, to save the landlord's mentally ill son and is marooned in an island named Monpura. There the servant comes across a fisherman's daughter.",
  },
  {
    id: uuidv4(),
    title: "Aguner Poroshmoni",
    genere: "drama",
    rating: "9.1",
    year: "1994",
    desc: "In the middle of the 1971;curfew is going on all over the Bangladesh. The liberation army is operated as effective guerrilla force - Badiul Alam is one them. Alam plans for starting guerrilla operation in the capital and hides himself in Mr. Matin's house. Mr. Matin lives with his loving wife Surma and two beautiful daughters Ratri and Opala. In association with other freedom fighters, Alam operates some successful guerrilla attacks against barbarous Pakistani military . But one after another his fellow freedom-fighters are getting caught by the military, tortured , murdered. Alam being shot and seriously injured is taken to Matin's house ; can he survive? Can he see the light of morning again ?",
  },
  {
    id: uuidv4(),
    title: "Haajar Bachhar Dhorey",
    genere: "drama",
    rating: "8.1",
    year: "2005",
    desc: "Sets around some rural people and their village dealing with their lifestyle, struggle of survival, religion, marriage, relations, death and this ongoing process.",
  },
  {
    id: uuidv4(),
    title: "Aynabaji",
    genere: "Thriller",
    rating: "9",
    year: "2016",
    desc: "Ayna is an actor and the prison is his stage. He slips into the characters of the powerful convicted in exchange of money and take their place in prison. This strange profession is borne out of a society that doesn't give him a chance to follow his passion of acting, but forces him to act in the real life. Falling in love with the girl next door changes his life equation and he decides to end this career with one last performance. But this one takes him too deep in the rabbit hole. The story unfolds on how an underdog survives in a society that is merciless and struggles his way out from the clutch of crime game in which he is a part too.",
  },
  {
    id: uuidv4(),
    title: "Hotath Bristi",
    genere: "Romance",
    rating: "8",
    year: "2016",
    desc: "A man and a woman fall in love through exchanging letters but destiny keeps separating them.",
  },
  {
    id: uuidv4(),
    title: "Srabon Megher Din ",
    genere: "drama",
    rating: "8.6",
    year: "2000",
    desc: "The second movie directed by Humayun Ahmed. A village drama interweave around a charming girl, a folk singer, his love interest and the local aristocratic family's involvement, the movie provide with some beautiful songs.",
  },
  {
    id: uuidv4(),
    title: "Bhooter Bhabishyat",
    genere: "Comedy",
    rating: "8.1",
    year: "2012",
    desc: "A rib-tickling comedy about a group of spirits who, in their various idiosyncrasies, try and save their only haunt, their resting place, when some unscrupulous builders try and break it down to build a modern monstrosity.",
  },
  {
    id: uuidv4(),
    title: "Padma Nodir Maji",
    genere: "Drama",
    rating: "8.2",
    year: "1993",
    desc: "Hossain, a Bengali Muslim wants to establish a little Utopia on an island in the Padma delta. He doesn't care if the people who populate it are Hindu or Muslim.",
  },
  {
    id: uuidv4(),
    title: "Belaseshe",
    genere: "Drama",
    rating: "8.5",
    year: "2015",
    desc: "A story of relationships that explores the intricacies of the married life, of life-long companionship, of promises and expectations and love.",
  },
];
